spring.application.name=MyGamingJournal

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DB_URL}/my_gaming_journal
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

rawg.api.key=${API_KEY}

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000